/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.egcc.app.view;

import javax.swing.JOptionPane;
import pe.egcc.app.controller.MateController;

/**
 *
 * @author Alumno
 */
public class Panel5Num extends javax.swing.JPanel {

    /**
     * Creates new form Panel2Num
     */
    public Panel5Num() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lbl_Numero1 = new javax.swing.JLabel();
        lbl_Numero2 = new javax.swing.JLabel();
        lbl_Numero3 = new javax.swing.JLabel();
        txt_Num3 = new javax.swing.JTextField();
        lbl_Numero4 = new javax.swing.JLabel();
        txt_Num1 = new javax.swing.JTextField();
        txt_Num4 = new javax.swing.JTextField();
        txt_Num2 = new javax.swing.JTextField();
        btn_Procesar = new javax.swing.JButton();
        lbl_Numero5 = new javax.swing.JLabel();
        txt_Num5 = new javax.swing.JTextField();

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setText("PROMEDIO DE CINCO NÚMEROS");
        jLabel1.setOpaque(true);

        lbl_Numero1.setText("Número 1: ");

        lbl_Numero2.setText("Número 2:");

        lbl_Numero3.setText("Número 3:");

        lbl_Numero4.setText("Número 4:");

        btn_Procesar.setText("Procesar");
        btn_Procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProcesarActionPerformed(evt);
            }
        });

        lbl_Numero5.setText("Número 5:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Numero5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_Numero2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_Numero1))
                            .addComponent(lbl_Numero3)
                            .addComponent(lbl_Numero4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txt_Num4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Num3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Num2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Num1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txt_Num5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Procesar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Numero1)
                    .addComponent(txt_Num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Procesar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Numero2)
                    .addComponent(txt_Num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Num3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Numero3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Num4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Numero4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Numero5)
                    .addComponent(txt_Num5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProcesarActionPerformed
        int n1= Integer.parseInt(txt_Num1.getText());
        int n2= Integer.parseInt(txt_Num2.getText());
        int n3= Integer.parseInt(txt_Num3.getText());
        int n4= Integer.parseInt(txt_Num4.getText());
        int n5= Integer.parseInt(txt_Num5.getText());
        
        MateController control = new MateController();
        
        int pr = control.promediar(n1, n2, n3, n4, n5);

        String repo="Promedio: " + pr;
        JOptionPane.showMessageDialog(this, repo);
    }//GEN-LAST:event_btn_ProcesarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Procesar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_Numero1;
    private javax.swing.JLabel lbl_Numero2;
    private javax.swing.JLabel lbl_Numero3;
    private javax.swing.JLabel lbl_Numero4;
    private javax.swing.JLabel lbl_Numero5;
    private javax.swing.JTextField txt_Num1;
    private javax.swing.JTextField txt_Num2;
    private javax.swing.JTextField txt_Num3;
    private javax.swing.JTextField txt_Num4;
    private javax.swing.JTextField txt_Num5;
    // End of variables declaration//GEN-END:variables
}
