/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.app.view;

import javax.swing.JOptionPane;
import pe.egcc.app.controller.AppController;
import pe.egcc.app.service.MyMath;

/**
 *
 * @author Gustavo Coronel
 */
public class FactorialView extends javax.swing.JInternalFrame {

  public FactorialView() {
    initComponents();
    lblResutlado.setText("");
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        lblResutlado = new javax.swing.JLabel();
        btnFactorial = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("FACTORIAL");

        jLabel1.setText("Número:");

        lblResutlado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblResutlado.setForeground(new java.awt.Color(0, 102, 102));
        lblResutlado.setText("jLabel2");

        btnFactorial.setText("Factorial");
        btnFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactorialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblResutlado)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFactorial)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFactorial))
                .addGap(55, 55, 55)
                .addComponent(lblResutlado)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactorialActionPerformed
            
        try{
            String dato = txtNumero.getText();
            if(dato.equals("")){
                JOptionPane.showMessageDialog(this, "El campo de texto no puede estar vacío!!!",
                        "Mensaje de Error",JOptionPane.ERROR_MESSAGE);
            }else{
                int numero = Integer.parseInt(dato);
                AppController control = new AppController();
                long factorial = control.calcularFactorial(numero);
                lblResutlado.setText(String.valueOf(factorial));
            }
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Ingrese un número correcto!","Mensaje de Error",
                    JOptionPane.ERROR_MESSAGE);
            txtNumero.setText("");
        }
        
    }//GEN-LAST:event_btnFactorialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFactorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblResutlado;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
