/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.app.view;

import javax.swing.JOptionPane;
import pe.egcc.app.controller.AppController;
import pe.egcc.app.service.MyMath;

/**
 *
 * @author Gustavo Coronel
 */
public class FibonacciView extends javax.swing.JInternalFrame {

  public FibonacciView() {
    initComponents();
    lblResutlado.setText("");
    lblReultTitle.setText("");
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNumero = new javax.swing.JTextField();
        btnPrimo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblResutlado = new javax.swing.JLabel();
        lblReultTitle = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("SERIE FIBONACCI");

        btnPrimo.setText("Fibonnaci");
        btnPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimoActionPerformed(evt);
            }
        });

        jLabel1.setText("Número:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPrimo)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrimo))
                .addGap(17, 17, 17))
        );

        lblResutlado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblResutlado.setForeground(new java.awt.Color(0, 102, 102));
        lblResutlado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResutlado.setText("jLabel2");
        lblResutlado.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        lblReultTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblReultTitle.setForeground(new java.awt.Color(0, 102, 102));
        lblReultTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReultTitle.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(341, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(277, 277, 277))
            .addComponent(lblResutlado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblReultTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblReultTitle)
                .addGap(28, 28, 28)
                .addComponent(lblResutlado, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimoActionPerformed
            
        try {
            String dato = txtNumero.getText();
            if (dato.equals("")) {
                JOptionPane.showMessageDialog(this, "El campo de texto no puede estar vacío!!!",
                        "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            } else {
                int numero = Integer.parseInt(dato);

                if (numero <= 0) {
                    JOptionPane.showMessageDialog(this, "El número ingresado tiene que ser mayor que cero!!!",
                            "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
                } else {
                    AppController control = new AppController();
                    int fibonacci[] = control.calcularFibonacci(numero);
                    String repo = "";
                    for (int i = numero - 1; i >= 0; i--) {
                        repo += (fibonacci[i]);
                        if (i > 0) {
                            repo += ", ";
                        }
                    }
                    lblReultTitle.setText("La serie Fibonacci es:");
                    lblResutlado.setText(repo);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un número correcto!", "Mensaje de Error",
                    JOptionPane.ERROR_MESSAGE);
            txtNumero.setText("");
        }

    }//GEN-LAST:event_btnPrimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPrimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblResutlado;
    private javax.swing.JLabel lblReultTitle;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
