/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.app.view;


import javax.swing.JInternalFrame;


/**
 * 
 * 
 * @author CHERRES
 */
public class FormularioMDI extends javax.swing.JFrame {

  
  FactorialView factorialView;
  FibonacciView fibonacciView;
  MCDView       mcdView;
  PrimoView     primoView;
    
  public FormularioMDI() {
    initComponents();
    setLocationRelativeTo(null);
    setExtendedState(MAXIMIZED_BOTH);
  }
  public void centrarVentanaInterna(JInternalFrame internalFrame){
        int x = (desktopPane.getWidth() / 2) - (internalFrame.getWidth() / 2);//Calculando posiciones x e y
        int y = (desktopPane.getHeight()/ 2) - (internalFrame.getHeight() / 2);
        if(internalFrame.isShowing()){//comprobando si la ventana está ejecutada
            internalFrame.setLocation(x, y);//si es así solo lo colocamos en la mitad
        }else{
            desktopPane.add(internalFrame);
            internalFrame.setLocation(x, y);
            internalFrame.show();
        }
    }
  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnTBFactorial = new javax.swing.JButton();
        btnTBMcdMcm = new javax.swing.JButton();
        btnFibonacci = new javax.swing.JButton();
        btnPrimo = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnSalir = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();
        menuOpciones = new javax.swing.JMenu();
        menuOpcionesFactorial = new javax.swing.JMenuItem();
        menuOpcionesMcdMcm = new javax.swing.JMenuItem();
        menuOpcionesFibonacci = new javax.swing.JMenuItem();
        menuOpcionesPrimo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnTBFactorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/app/img/calculadora-de-factorial.jpg"))); // NOI18N
        btnTBFactorial.setToolTipText("Factorial");
        btnTBFactorial.setFocusable(false);
        btnTBFactorial.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTBFactorial.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTBFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesFactorialActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTBFactorial);

        btnTBMcdMcm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/app/img/leica-boton-disparo-m-8mm-negro.jpg"))); // NOI18N
        btnTBMcdMcm.setToolTipText("MCD y MCM");
        btnTBMcdMcm.setFocusable(false);
        btnTBMcdMcm.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTBMcdMcm.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTBMcdMcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTBMcdMcmActionPerformed(evt);
            }
        });
        jToolBar1.add(btnTBMcdMcm);

        btnFibonacci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/app/img/fibonacci_e_tao_facil_quanto_1_1_2_3_boton_redondo_2_54cm-r60503b1490b24ff8a456f253b70017a5_x7j12_8byvr_324.jpg"))); // NOI18N
        btnFibonacci.setToolTipText("Fibonacci");
        btnFibonacci.setFocusable(false);
        btnFibonacci.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFibonacci.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFibonacciActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFibonacci);

        btnPrimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/app/img/Logotipo-pinterest-png-0.png"))); // NOI18N
        btnPrimo.setToolTipText("Primo");
        btnPrimo.setFocusable(false);
        btnPrimo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrimo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnPrimo);
        jToolBar1.add(jSeparator1);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/egcc/app/img/23390.png"))); // NOI18N
        btnSalir.setToolTipText("Salir");
        btnSalir.setFocusable(false);
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSalir);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        menuOpciones.setMnemonic('h');
        menuOpciones.setText("Opciones");

        menuOpcionesFactorial.setMnemonic('c');
        menuOpcionesFactorial.setText("Factorial");
        menuOpcionesFactorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesFactorialActionPerformed(evt);
            }
        });
        menuOpciones.add(menuOpcionesFactorial);

        menuOpcionesMcdMcm.setMnemonic('a');
        menuOpcionesMcdMcm.setText("MCD y MCM");
        menuOpcionesMcdMcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesMcdMcmActionPerformed(evt);
            }
        });
        menuOpciones.add(menuOpcionesMcdMcm);

        menuOpcionesFibonacci.setText("Fibonacci");
        menuOpcionesFibonacci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesFibonacciActionPerformed(evt);
            }
        });
        menuOpciones.add(menuOpcionesFibonacci);

        menuOpcionesPrimo.setText("Primo");
        menuOpcionesPrimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcionesPrimoActionPerformed(evt);
            }
        });
        menuOpciones.add(menuOpcionesPrimo);

        menuBar.add(menuOpciones);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

  private void menuOpcionesFactorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesFactorialActionPerformed
        if(!(factorialView instanceof FactorialView)){
            factorialView = new FactorialView();
        }
        centrarVentanaInterna(factorialView);
  }//GEN-LAST:event_menuOpcionesFactorialActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void menuOpcionesMcdMcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesMcdMcmActionPerformed
        if(!(mcdView instanceof MCDView)){
            mcdView = new MCDView();
        }
        centrarVentanaInterna(mcdView);
    }//GEN-LAST:event_menuOpcionesMcdMcmActionPerformed

    private void btnTBMcdMcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTBMcdMcmActionPerformed
        if(!(mcdView instanceof MCDView)){
            mcdView = new MCDView();
        }
        centrarVentanaInterna(mcdView);
    }//GEN-LAST:event_btnTBMcdMcmActionPerformed

    private void menuOpcionesFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesFibonacciActionPerformed
        if(!(fibonacciView instanceof FibonacciView)){
            fibonacciView = new FibonacciView();
        }
        centrarVentanaInterna(fibonacciView);
    }//GEN-LAST:event_menuOpcionesFibonacciActionPerformed

    private void btnPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimoActionPerformed
        if(!(primoView instanceof PrimoView)){
            primoView = new  PrimoView();
        }
        centrarVentanaInterna(primoView);
    }//GEN-LAST:event_btnPrimoActionPerformed

    private void menuOpcionesPrimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcionesPrimoActionPerformed
        if(!(primoView instanceof PrimoView)){
            primoView = new  PrimoView();
        }
        centrarVentanaInterna(primoView);
    }//GEN-LAST:event_menuOpcionesPrimoActionPerformed

    private void btnFibonacciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFibonacciActionPerformed
        if(!(fibonacciView instanceof FibonacciView)){
            fibonacciView = new FibonacciView();
        }
        centrarVentanaInterna(fibonacciView);
    }//GEN-LAST:event_btnFibonacciActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FormularioMDI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FormularioMDI().setVisible(true);
        new FormularioMDI().setLocationRelativeTo(null);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFibonacci;
    private javax.swing.JButton btnPrimo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTBFactorial;
    private javax.swing.JButton btnTBMcdMcm;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuOpciones;
    private javax.swing.JMenuItem menuOpcionesFactorial;
    private javax.swing.JMenuItem menuOpcionesFibonacci;
    private javax.swing.JMenuItem menuOpcionesMcdMcm;
    private javax.swing.JMenuItem menuOpcionesPrimo;
    // End of variables declaration//GEN-END:variables

}
